#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.11
# In conjunction with Tcl version 8.6
#    Mar 21, 2018 10:36:21 PM


import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True
def set_Tk_var():
    global var1
    var1 = StringVar()

def Connect():
    print('gui2_support.Connect')
    
    var1.set('Ovo je prvi redak')

    sys.stdout.flush()
    

def Settings():
    global var1;
    print('gui2_support.Settings')
    var1=var1+var1
    sys.stdout.flush()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None


def Upis():
    var1=input("Unesi nesto aj molim te: ")
    

if __name__ == '__main__':
    import gui2
    gui2.vp_start_gui()


